#!/bin/sh
  #
  # Configuring host communication.
  #
  
  case "$1" in
    start)
  	printf "Configuring host communication."
  	
  	/sbin/ifconfig eth0 192.168.1.10 up
  	/sbin/route add -host 200.135.92.234 dev eth0
  	/sbin/route add default gw 200.135.92.234


  	printf "Running WEB Server"
    python ../etc/init.d/pyServer.py&
  	[ $? = 0 ] && echo "OK" || echo "FAIL"
  	;;
    stop)
  	printf "Shutdown host communication. "
  	/sbin/route del default
  	/sbin/ifdown -a
  	[ $? = 0 ] && echo "OK" || echo "FAIL"
  	;;
    restart|reload)
  	"$0" stop
  	"$0" start
  	;;
    *)
  	echo "Usage: $0 {start|stop|restart}"
  	exit 1
  esac
  
  exit $?
